# Generated by Django 6.0.1 on 2026-01-19 22:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(max_length=128, unique=True)),
                ('common_options', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['type_id'],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('directory_number', models.CharField(max_length=32)),
                ('registration_account', models.CharField(max_length=64)),
                ('registration_password', models.CharField(max_length=256)),
                ('is_shared', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SIPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=5060)),
                ('transport', models.CharField(choices=[('TLS', 'TLS'), ('UDP', 'UDP'), ('TCP', 'TCP')], default='UDP', max_length=4)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('primary_sip_server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_sites', to='core.sipserver')),
                ('secondary_sip_server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_sites', to='core.sipserver')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='MAC address must be 12 hex characters (colon optional)', regex='^[0-9A-Fa-f]{2}(:?[0-9A-Fa-f]{2}){5}$')])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('device_type_id', models.CharField(max_length=128)),
                ('device_specific_configuration', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('line_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_devices', to='core.line')),
                ('lines', models.ManyToManyField(blank=True, related_name='devices', to='core.line')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='core.site')),
            ],
            options={
                'ordering': ['mac_address'],
            },
        ),
    ]
