# Generated by Django 6.0.1 on 2026-01-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_site_timezone_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_provisioned_at',
            field=models.DateTimeField(blank=True, help_text='Last time device configuration was requested', null=True),
        ),
    ]
