# Generated by Django 6.0.1 on 2026-01-21 03:15

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_last_provisioned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='registration_password',
            field=core.fields.EncryptedCharField(max_length=512),
        ),
    ]
