# Generated by Django 6.0.1 on 2026-02-03 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_line_phone_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dial plan name', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of dial plan purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='site',
            name='dial_plan',
            field=models.ForeignKey(blank=True, help_text='Dial plan for phone number transformation at this site', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='core.dialplan'),
        ),
        migrations.CreateModel(
            name='DialPlanRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_regex', models.CharField(help_text='Input pattern (standard format with X, *, [], [^], ())', max_length=512)),
                ('output_regex', models.CharField(help_text='Output pattern with $1, $2, etc. for capture groups', max_length=512)),
                ('sequence_order', models.PositiveIntegerField(default=0, help_text='Rule execution order (ascending)')),
                ('dial_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.dialplan')),
            ],
            options={
                'ordering': ['dial_plan', 'sequence_order'],
                'constraints': [models.UniqueConstraint(fields=('dial_plan', 'sequence_order'), name='unique_dial_plan_rule_order')],
            },
        ),
    ]
